[theme]
base = "dark"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
primaryColor = "#7C3AED"
textColor = "#F0F6FC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
